---
# nginx-related configuration
nginx:
    location: /etc/nginx/conf.d/ # where to put virtual hosts configs
    template:
        | # template for virtual host configs, seet `text/template` package description for syntax
        upstream {{ .UpstreamName }} {
            {{ range $server := .Servers }}
                server {{ $server.Host }}:{{ $server.Port }} {{ $server.Options }};
            {{ end }}
        }

        server {

            listen 80;
            server_name {{ .DomainName }};

            location / {
                proxy_pass http://{{ .UpstreamName }};

                include    proxy.conf;
            }
        }
