---
nginx:
  location: /etc/nginx/conf.d/
  template: |
    upstream {{ .UpstreamName }} {
        {{ range $server := .Servers }}
            server {{ $server.Host }} {{ $server.Options }};
        {{ end }}
    }

    server {

        listen 80;
        server_name {{ .DomainName }};

        location / {
            proxy_pass http://{{ .UpstreamName }};
        }
    }
