# workflow name
name: CI

# trigger events
on:
  push: {}
  pull_request: {}

# jobs to run
jobs:
  # job 1: test go module
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # step 1: set up go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      # step 2: checkout repository code
      - name: Checkout code into workspace directory
        uses: actions/checkout@v4

      # step 3: install dependencies
      - name: Install all Go dependencies
        run: go mod download

      # step 4: run test
      - name: go test
        run: go test ./...
